spring:
    datasource:
        url: jdbc:h2:tcp://localhost/~/miniproject
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
            # show_sql: true
            format_sql: true
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html

# logging:
#     level:
#         root: debug
#         org.hibernate.SQL: debug
#         # org.hibernate.type: trace
#         # com.parfait.study.simplelogging.service.SomeService: info
#         com.parfait.study.simplelogging.service.SomeService: debug
#         me.steell.miniproject: debug

#logBack dev, prod 설정
spring.profiles.include: dev
# spring.profiles.include: prod
